### ISSUE TITLE
Mod Loading Failure

### ISSUE THREAD

**Issue by Coraline77447** [congueror/CLib#2]
Hi! I've encountered an issue after mod loading had finished loading in all of the mods I'm using while I was loading/playing modded Minecraft Java Edition 1.16.3. I wanted play with this mod but there's a problem with it apparently... Here's what's the most important piece of the crash report down below but if you need the whole entire crash report then I can give it to you so you can fix the issue that I'm experiencing! Thanks! P.S> This is my very first time reporting an issue about a mod on here and this issue is my very first issue with a mod that I've encountered after the mod loading process had finished and sadly I'll have to uninstall your mods till this issue with CLib is fixed... But I'm going to retry to load in with CLib and if it works then simply ignore this but if it happens again caused by the same issue then I'll reply to this post confirming that the retry has failed. Also sorry that this post is a bit too long to read! 

Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[?:?] {re:classloading}
at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:494) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.util.Util.func_215077_a(Util.java:418) ~[?:?] {re:classloading,xf:OptiFine:default}
at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:490) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) ~[?:?] {re:classloading,xf:OptiFine:default}
at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:184) ~[ForgeOptiFine%201.16.3.jar:?] {re:classloading,pl:runtimedistcleaner:A}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.3-34.1.1.jar:34.1] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {re:classloading}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {re:classloading}

**Comment by Coraline77447** [comment]
I'd just tried it again and the same issue has occurred again...(see photo below) Since I've confirmed that I'm still experiencing the same problem with CLib then please don't ignore my main post! Again if you need the entire crash report then please ask and I'll send it to you on here.

![20201001_233559](https://user-images.githubusercontent.com/72243304/94891363-13688600-043f-11eb-96d7-927baee95cdf.jpg)

**Comment by marios-andr** [comment]
Thanks for reporting, I'll investigate and get back to you as soon as possible. Also, please provide me with the latest.log found in rootdir > logs (or the log which is the date when you tried to launch my mod).
Edit: As well as with the mod list if you can.

**Comment by Coraline77447** [comment]
Here's the log when I'd first tried CLib and it failed after forge completely finished with mod loading. Btw I've finished with my play session without CLib, SimpleOres2, SimpleCoreLib, and CArmoury which I wish I could have more fun with them in my "modpack"... (what I really mean by modpack is that I currently have almost 40 mods in my mods folder so it's not an actual modpack.)

[2020-10-01-7.log.gz](https://github.com/congueror/CLib/files/5318742/2020-10-01-7.log.gz)

**Comment by marios-andr** [comment]
I believe you got the wrong log because here it says you actually managed to join a world. Also please refrain from sending the full files, because then I have to download them, so instead use something like https://pastebin.com (you can select all text on screen by pressing ctrl+A if you didn't know). Also why did you stop using SimpleOres2, SimpleCoreLib was it also causing issues?

**Comment by Coraline77447** [comment]
Why I'd uninstalled SimpleOres2 and its core mod is cause I'd thought that without CArmoury I wouldn't be able to use SimpleOres2's new materials like Copper or Tin or any other ore that SimpleOres2 provides and I've now realized that CLib has no control over SimpleOres2 and its core mod SimpleCoreLib also my bad for providing the wrong log cause I'd thought it said 10-1 (October 1st) which is when I'd first tested the mod also theres some logs that says almost the same thing except for the last number (i.g. 10-1-6 10-1-5 10-1-4 ect). Btw I dont have a application that can open log files so I cant read every log in my .minecraft/logs folder to find the right log that'll tell what was really going on behind the scenes. Remember, this is my first time reporting a issue for a mod cause normally I wouldn't have any problems with a mod even if its still in development like CLib is in beta still (I understand that I was testing CLib while its still in its development stages and any mod that's in the development process will have problems like what I'm going through with CLib right now) and if I do run into a issue with a mod in any development state it's currently in then I would find a solution to the problem without reporting the issue or simply uninstall the mod cause I would be fine without the mod but I would keep an eye out for its next update that might or might not fix it's problem (I.g. Item Physic Lite mod for ForgeOptiFine1.16.2 isn't working for me when it used too back when I'd played modded 1.12.2 and Item Physic Full for ForgeOptiFine1.12.2 wasn't working for me at the time while its 1.16.2 version is working for me now). Also I'm wondering if you could maybe help me find the right log so that I can help you fix the problem that CLib is experiencing? If you have the time to do that that is. P.S. sorry for the late reply, I was watching some videos when you replied and then I was asleep till after 5:30PM (my time btw), and that this comment is a bit too long to read...

**Comment by marios-andr** [comment]
Thank you for the understanding, also you do not have to explain yourself to me after all am here to help you. You can view the log files by downloading something like [WinRAR](https://www.win-rar.com/start.html?&L=0) or [7Zip](https://www.7-zip.org) . As for the right crash log, am not sure how I can be of help. If it's not too much trouble I suggest you download the mod again and then send the latest.log as it will save both of us a little bit of time. Additionally I'd like to know what platform you are using to launch your modpack(Twitch, Minecraft Launcher, MultiMC, etc)

**Comment by Coraline77447** [comment]
I'm using TLauncher to launch my game since I'm unfortunately a cracked client user (been one ever sense I started playing java edition back in 2016 or so when minecraft was at 1.10.2) since I don't have any money to officially get minecraft sadly and I'd though I had installed 7Zip or WinRAR so I'm gonna go check if I have ether one of those installed on my laptop and I'll redownload and reinstall CLib and try to locate that log file it'll create when it'll cause me to crash again. alrighty

**Comment by Coraline77447** [comment]
so.....i do have 7Zip and I redownloaded and reinstalled CLib, took out all 40 of the mods in my mods folder and fired up TLauncher with only CLib installed and now I'm at the title screen....... Idk exactly why I was experiencing that issue when I apparently and simply had to just redownload and reinstall the mod but this doesn't exactly solve the issue tho cause what if someone else were to download and install CLib for the very first time and this issue happens to them? The problem will remain in CLib till you and I get this problem fixed once and for all so instead of what you said as of redownloading and reinstalling CLib Ima try to go find that first log file it created when I'd very first started forge to load in CLib. I know that I don't need to do this but I don't want anybody else to have to go through the same situation as I did cause I want everyone to enjoy your mod and the fact that CLib is a independency for your other mod CArmoury (I know that you already know that CLib is a independency cause you made the mod).

**Comment by Coraline77447** [comment]
I may have actually found the right log this time. Hope this helps!

[2020-10-01-6.log](https://github.com/congueror/CLib/files/5322619/2020-10-01-6.log)

Edit/Update: I have installed all 40 of the mods I had in the mods folder and then I had put in CArmoury and I encountered the problem again. Now I'm testing to see if CLib will work with the other mods in my mods folder and if I'm at the title screen then the problem is happening between CLib and CArmoury unfortunately. But if im not at the title screen then that means that CLib isn't working with any mods within my mods folder which means CLib isn't working with any other mods in general. Btw i'm not at the title screen cause the same problem has happened again so CLib isn't working with any other mod I have in my mods folder including CArmoury.

**Comment by marios-andr** [comment]
So since you are on TLauncher that means you are using a premade-modpack, yes? Can you send me the name of the premade-modpack you are using or if it's your own modpack, the list of all the mods you have installed(perhaps a screenshot or something)?

Edit: I have found out that my mod is conflicting with another mod you have installed, but in order to find it you must send me your modpack and any additional mods that you may have

**Comment by Coraline77447** [comment]
my "modpack" or "premade modpack" is latterly just a bunch of mods in my mods folder but ill give ya the list of mods I have and I'd recently downloaded two mods that had updates which they're in development state (Alpha) which those two mods are Bookshelf (1.16.3-8.4.14) and Enchantment Descriptions (1.16.3-5.0.5)

**Comment by Coraline77447** [comment]
Since you asked what mods I have that may be conflicting with CLib then here's what's in my mods folder: 

*Some of these mods does work in both 1.16.2 and 1.16.3 in their latest versions even tho they say 1.16.2 when I'm playing in 1.16.3!*

1.12.2 (file folder, not a mod)
memory_repo (file folder, not a mod)
*[1.16.2][Forge]+RPG-HUD-3.8.2*
allthemodium-1.1.3-1.16.3-34.1.0
*AppleSkin-mc1.16.2-forge-1.0.14* 
*BetterMineshaftsForge-1.16.2-1.0*
Bookshelf-1.16.3-8.4.14
bspawncontrol_1.16.3_1.1
Clumps-6.0.0.11
collective-1.16.3-1.41
EnchantmentDescriptions-1.16.3-5.0.5
enchantwithmob-1.16.3-1.6.0
FastLeafDecay-v25
forgemod_VoxelMap-1.10.11_for_1.16.3
*globalxp-1.16.2-v1.4.13* (I'm experiencing a grapgical glitch(s) with this mod when I look at the globalxp block since I have the block in my attic in my house on the modded survival world I'm currentlly playing on and it's making my chests and my bed look really strange...)
*grid-1.16.2-forge33.0.5-1.6.1*
*Hwyla-forge-1.10.11-B78_1.16.2*
infinitymending-1.0
ironchest-1.16.3-11.2.6
jei-1.16.3-7.3.2.30
Ma-Enchants-1.16.3-3.4.0
mcw-bridges-1.0.4-mc1.16.3
mcw-doors-1.0.0-mc1.16.3
mcws-roofs-1.16.3-v2.0.0
mcw-windows-1.0.2-mc1.16.3
mining-helmet-1.16.3-1.0.9
ModernUI-1.16.3-2.2.0.64-universal
OptiFine-OptiFine-1.16.3_HD_U_G3
prefab-1.6.2.1
rare-ice-0.2.2
repurposed_structures-1.16.3-2.2.2
ScalingHealth-1.16.3-4.0.0+0 
*SilentLib-1.16.2-4.8.0+60*
SimpleCoreLib-1.16.3-2.0.0.5
SimpleOres2-1.16.3-2.3.0.2
tl_skin_cape_forge_1.16.3-1.13
*toolleveling-1.16.2-1.0.0*
TrampleStopper-2.2.0+build.1.mcVersion.1.16.3 (this mod is supposed to prevent farmland from getting trampled but the farmland is still getting trampled so I might remove this mod cause it does not doing anything and that its useless if its main feature was supposed to prevent farmland from getting trampled and farmland still gets trampled anyways...)
TrashSlot_1.16.3-12.2.0
villagerdeathm_1.16.3_1.5
*WailaHarvestability-mc1.16.2-forge-1.1.13*
WAWLA-1.16.3-6.0.1

**Comment by Coraline77447** [comment]
I have just found out which mod is causing this issue which is a mod called Rare Ice. What Rare Ice mod is is a mod that puts in rare items like diamond, emerald, coal, and other rare items in the game into a ice block for you to find when you're in a cold biome i.g Snowy Taiga, Ice Plains, Ice Spikes, Ice River/Frozen River, etc. I may know what's causing this issue which may be a confliction between CLib and Rare Ice. Rare Ice is apparently trying to input the materials that CLib provides into a rare ice block for you to find (i.g. Aluminum, Lead, Copper, Ruby, Silver, Lumium, Nickel, Invar, Electrum, Pyrotheum Dust, Sulfur, Platinum, Enderium, Signalum, Coal Nugget, Tungsten, Bronze, Amethyst, Sapphire, Opal, Titanium, Uranium, Cobalt, and Zinc). Apparently CLib doesn't like Rare Ice tryin to put in all of the materials that CLib provides into a rare ice block. I may be wrong about what I said but that's what I think is possibly going on between CLib and Rare Ice. So now I'm askin if both you and the owner of Rare Ice to have compatibility with each other but I know that you may not want; Pyrotheum Dust, Platinum, Enderium, Signalum, Tungsten, Titanium, Uranium, Cobalt, and possibly won't allow the carftable materials like bronze, Invar, and all the other craftable materials to be compatible with Rare Ice for Rare Ice to add them into rare ice blocks cause I know that you want us players to have to work for it to get them and want us to have to go get some of them from the nether cause that's the challenge of obtaining these materials. Am I correct?

**Comment by marios-andr** [comment]
You are correct and thank you for finding the conflicting mod, I'll take a look at rare ice and see what I can do on my part.

**Comment by Coraline77447** [comment]
Btw took me like an hour or so to find the conflicting mod by putting in one mod at a time then 3 at a time eventually, had to remove Rare Ice mod and had to restart/recreate the world I was playing on for ore generation purposes since I had already loaded in so many chunks in the world and I'm not willing to go extremely far and wide just to find all of the new ores. Except for the new ores that I added before I restarted the world and the new ores (by SimpleOres2) were generated but in some pretty far away chunks. At least in the world I recreated doesn't have a cold biome cause I haven't found one yet so I haven't found any rare ice blocks yet (especially since I don't have Rare Ice mod installed yet sadly...) P.S. I know that I didn't have to write this reply but I wanted to cause I wanted to let you know my experiences when I was finding out which mod was conflating with CLib and I was telling you all of this as if we're friends even tho we've never met in person and online before till a few days ago when I reported the issue. Btw if you want to be friends with me then that's fine but if not then that's fine as well but at least I've been helping you with fixing your mod by providing you with the conflicting mod and I can't wait to see if you would allow a small few of the materials (i.g. like Lead, Copper, Silver, tin, sulfur, nickel, coal nugget, and Opal, you know the low teir materials that makes low tier armors, tools, and swords and maybe some bows made out of these materials like maybe a copper bow, tin bow, nickel bow, silver bow, and opal bow?) that CLib adds into the game to be in rare ice blocks. Also I have a suggestion, (even though this isn't the right place to have a suggestion but why not?) could you please add in some bows that are made out of some of the materials that's in CLib? Like how SimpleOres2 allows us to make 2 bows (one out of Mithral and the other out of  Onyx, (btw Onyx is a materia/ore that SimpleOres2 has) I possibly and already know that you may not allow us to craft bows out of high tier materials (i.g. Platinum, Enderium, Signalum, Tungsten, Titanium, and Uranium) but if you do allow us to craft bows out of the mid teir and high teir materials then that'll make CLib awesome

**Comment by Coraline77447** [comment]
P.P.S. "thank you for finding the conflicting mod" you're welcome

**Comment by marios-andr** [comment]
This error should know be fixed in version 1.4.0 thank you for your cooperation.
