### ISSUE TITLE
Datapack Errors Apon World Loading/ World Creation

### ISSUE THREAD

**Issue by Coraline77447** [congueror/CLib#3]
Hi! It's me again and why I'm back here is cause when I was trying to load a currently saved world and I've encountered this: 

"Errors in currently selected datapacks prevented the world from loading. You can either try to load it with only the vanilla data pack ("safe mode"), or go back to title screen and fix it manually."

                                 [          Safe Mode         ]   [      Back to Title Screen      ]

This issue happened when I tried to load into my world called Coraline World 1.16.4 (Modded) and thought that Forge's experimental settings broke yet again by adding in mods so I decided to delete that world and try to create a new world and ended up at the same screen again so I had to narrow down which mod out of say 10+ mods I've downloaded and installed to find out that CLib is having issues with me yet again....(Btw I'm using the latest version of the mod for Forge 1.16.4.) I bet that I'm not the only one with this issue however. Anyways Here's the log: 

[2020-11-05-7.log](https://github.com/congueror/CLib/files/5494186/2020-11-05-7.log)

Btw when I was looking through the log to see if I'm sending the correct log and I saw ALOT of errors from: CLib, MoreVanillaWeapons, and possibly two more mods. So when you can or if you can/want too maybe you could tell the owners of these mods that they have some datapack issues that needs resolving? I know that I need to report this issue with those mods but why would I report basically the same thing on their issue trackers when I've already reported the issues on here? Why can't you help me to help them make their mods better by telling them that there's some issues with their mods by providing them with my log which has the information they need to fix these datapack issues?.... P.S. How on earth can I manually fix the errors with the selected datapacks anyways?!? I'm no modder... I wish I was a modder tho but javascript looks and is possibly too hard to understand for me since I was born with a mental disorder and that I don't have that much patience or time to make a mod myself... I hope this ain't too much to read btw...

P.P.S. This is off topic but...when will CArmoury gonna be ported/updated to 1.16.4?

**Comment by marios-andr** [comment]
I can't seem to be able to recreate this issue nor can I find any errors concerning my mod. So I have no idea why this is happening to you. Make sure you have forge 35.0.7+ and have updated all your mods. Further than this there's nothing I can do to help you, hope you figure it out. Also CArmoury was released 1 day ago.

**Comment by Coraline77447** [comment]
I'll try Clib again since I've gotten nearly all of the mods in my mods folder and optifine up to date from 1.16.3 to 1.16.4 but if I still experience this issue then it must be that Clib could be conflicting with one of the mods in my mods folder since I may be the only one whos been experiencing this issue but here's my problem with the forge version. The the devs of Tlauncher (I use Tlauncher to launch the game for both vanilla and modded) takes their sweet time updating the forge versions on their end so the only way to get the latest version of forge is to update forge manually either by putting forge's .jar file in the mods folder or manually install forge and make Tlauncher launch that forge version that's not supported by the launcher to load custom skins and with optifine and would have to have a .jar file of optifine in the mods folder. I have tried this and every single time when I look at what forge version it is in the mods tab in the main title screen it always says the wrong version cause the game is apparently using TLauncher's forge version which overrides the new forge verion that would've been manually installed/added to mods folder as a .jar file and I don't know how to fix that and there's no way to manually update the froge version within Tlauncher itself which means I would have to wait till they update the forge version on their end... P.P.S. I have said that when I looked into the log file for when it happened and I saw ALOT of errors relating to modpacking from other mods, not just from Clib (which CLib does have some modpacking errors but the majority of the modpack errors are comming from other mods like mvw aka MoreVanillaWeapons mod. So in this case since I've discovered some modpacking errors from that mod and other mods. I guess I'll have to go report the modpack errors to the owners of the other mods that have modpack errors like mvw but I'm not gonna go report the modpack errors to the other mods right now cause I'm going to start my modded minecraft 1.16.4 play session....Also I know that I've said this alot of times already but I'm serious tho cause ALOT of people these days don't like, want, or have time to read really, really, really, long comments, replies, and messages so that's why I'll continue to say that I hope this comment, reply, or message isn't too long or too much to read. ok.......)

**Comment by Coraline77447** [comment]
UPDATE; my game crashed apon laoding into a pre-existing world and the crash is about the mouseClick event handler exception. Have I reported an issue that's alike this one? Btw here's the crash report and Log this time around which is different than the last crash;

https://pastebin.com/pdt9uavk

[2020-11-09-1.log.gz](https://github.com/congueror/CLib/files/5509702/2020-11-09-1.log.gz)

I'm going to remove Clib from the mods folder and try to load into my saved world or by making a new world and see if I can load into a world or make a new one. If I do load into a saved world or created a new one successfully then the issue is within Clib but if its the opposite that I'm not successful to load into a world or create a new world. Btw I managed to make Tlauncher use the latest version of forge, so forge version isn't the problem like how I'd thought it would've been.

UPDATE 2; I have successfully loaded into my saved world without CLib, so the latest crash was/is affected by a issue within CLib but we still don't know exactly what's causing CLib to not work with me and possibly many other people and I'm doing my best to help you fix the problems that Clib has....

**Comment by marios-andr** [comment]
I have no idea why this is happening since I don't do anything with the mouseClick event. Please attempt to remove all other mods except CLib and launch a new world(no need to delete old ones). If it works then it's probably a conflict with another mod. Also I highly suggest using MultiMC(I use it as my main minecraft launcher). Also you should probably avoid writing long comments as, as you said, not many people have enough time or patience to read all that.
